---
sudo: false
language: ruby
cache:
- bundler
- directories:
  - $HOME/.m2
rvm:
- jruby-1.7.25
before_install:
- git clone -b feature/event_interface https://github.com/elastic/logstash
- bundle exec rake vendor
- bundle exec rake install_jars
script:
- bundle exec rspec spec
jdk: oraclejdk8
